class ProvenanceIntelligenceLayer:

    def reconstruct_chain(self, input_data, reasoning_result):
        chain = []

        metadata = input_data.get("metadata", {})
        exif = input_data.get("exif", {})
        image_info = input_data.get("image_info", {})

        origin = reasoning_result.get("origin", {}).get("label", "")
        adversarial = reasoning_result.get("adversarial", {})

        if origin == "Synthetic / AI-Generated":
            chain.append("Likely generated by an AI image system")

        if origin == "Camera Capture":
            chain.append("Likely captured by a physical camera")

        if origin == "Screenshot":
            chain.append("Likely captured or reposted as a screenshot")

        if not exif:
            chain.append("EXIF metadata appears missing or stripped")

        if image_info.get("has_screen_dimensions"):
            chain.append("Image dimensions match common screen/screenshot patterns")

        if adversarial.get("risk_score", 0) >= 45:
            chain.append("Possible attempt to conceal, alter, or launder media origin")

        software = str(metadata.get("software", "")).lower()

        if software:
            chain.append(f"Software metadata detected: {software}")

        if not chain:
            chain.append("Insufficient evidence to reconstruct a reliable provenance chain")

        return chain

    def estimate_provenance_confidence(self, reasoning_result):
        consensus_score = reasoning_result.get("consensus", {}).get("consensus_score", 0)
        adversarial_score = reasoning_result.get("adversarial", {}).get("risk_score", 0)

        if adversarial_score >= 75:
            return "Low"

        if consensus_score >= 75:
            return "High"

        if consensus_score >= 45:
            return "Moderate"

        return "Low"

    def build_provenance_report(self, input_data, reasoning_result):
        chain = self.reconstruct_chain(input_data, reasoning_result)
        confidence = self.estimate_provenance_confidence(reasoning_result)

        return {
            "provenance_confidence": confidence,
            "probable_chain": chain,
            "note": (
                "This is an evidence-based provenance estimate, not absolute proof. "
                "Stronger provenance requires original files, timestamps, trusted capture records, "
                "cryptographic signatures, or verified chain-of-origin data."
            ),
        }
